sqlite_path: ./var/anaqram.sqlite

problems:
- "りんご"
- "ゴリラ"
- "ラッパ"
- "パンダ"
- "スイス"
- "スライド"
- "トンネル"
- "アップル"
- "オレンジ"
- "パソコン"
- "ハリネズミ"
- "とうきょう"
- "エベレスト"
- "ランドセル"
- "カブトムシ"
- "カルボナーラ"
- "オリンピック"
- "スマートホン"
- "しんかんせん"
- "やまのてせん"
- "あなくらむ！"
