name:                anaqram-server
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/anaqram-server#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - dotenv
  - elm-export
  - http-api-data
  - monad-logger
  - persistent
  - persistent-postgresql
  - persistent-template
  - resourcet
  - servant
  - servant-ede
  - servant-elm
  - servant-kotlin
  - servant-server
  - text
  - transformers
  - stm
  - unordered-containers
  - warp

library:
  source-dirs: src
  exposed-modules:
    - DB
    - Score
  other-modules: []
  ghc-options: -fno-warn-orphans

executables:
  server:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - anaqram-server
    other-modules: []

tests:
  generateElm:
    source-dirs: app
    main: GenerateElm.hs
    dependencies:
      - anaqram-server
      - shelly
    other-modules: []
  generateKotlin:
    source-dirs: app
    main: GenerateKotlin.hs
    dependencies:
      - anaqram-server
      - shelly
    other-modules: []
