name:                anaqram-server
version:             1.0.0
homepage:            https://github.com/matsubara0507/anaqram-server#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

- BlockArguments
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiWayIf
- NumericUnderscores
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RankNTypes
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- extensible >= 0.6.1
- mix
- mix-json-logger
- fallible
- elmap
- servant-elmap
- extensible-elmap
- servant-server
- yaml
- random
- warp
- servant-blaze
- blaze-html
- http-api-data
- mix-plugin-persistent-sqlite
- persistent
- persistent-template
- persistent-sqlite
- th-lift-instances

library:
  source-dirs: src

executables:
  server:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - anaqram-server
    - githash
    - dotenv

tests:
  generate-elm:
    main: GenerateElm.hs
    source-dirs: test
    dependencies:
    - anaqram-server
