resolver: lts-14.7
packages:
- .
extra-deps:
- extensible-0.6.1
- membership-0
- github: matsubara0507/mix.hs
  commit: 90e9f0ff462aba2e78498e57fad1f8bec1e68260
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-persistent-sqlite
  - helper/rio-logger-ext
- github: matsubara0507/fallible
  commit: dfbdce1a0b0c71bcfcea844c94f9cb815f071235
- github: matsubara0507/elmap.hs
  commit: a1539c3be6e8b5757a2a10a55e7c1b19c1fc76fd
  subdirs:
  - elmap
  - servant-elmap
  - extensible-elmap

docker:
  repo: matsubara0507/stack-build
  enable: false
