resolver: nightly-2017-10-13
packages:
  - .
  - location:
      git: https://github.com/matsubara0507/Shelly.hs
      commit: 9b39825d644349a73f688352d41ce06ee8634d18
    extra-dep: true
extra-deps:
  - servant-ede-0.6
  - shelly-1.6.8.4
flags: {}
extra-package-dbs: []
