resolver: lts-9.9
packages:
  - .
extra-deps:
  - servant-ede-0.6
flags: {}
extra-package-dbs: []

image:
  container:
    name: "anaqram"
    base: "fpco/stack-build"
    add:
      config: /app/config
      data: /app
      script: /usr/local/bin/
      static: /app/static
    entrypoints: ["entrypoint.sh"]

